CREATE TABLE "Account" ("id" TEXT PRIMARY KEY, "githubId" TEXT NOT NULL UNIQUE, "login" TEXT NOT NULL, "avatarUrl" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "DeviceGrant" ("id" TEXT PRIMARY KEY, "deviceCodeHash" TEXT NOT NULL UNIQUE, "userCode" TEXT NOT NULL UNIQUE, "clientName" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "approvedAt" TIMESTAMP(3), "consumedAt" TIMESTAMP(3), "accountId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ApiToken" ("id" TEXT PRIMARY KEY, "tokenHash" TEXT NOT NULL UNIQUE, "scope" TEXT NOT NULL DEFAULT 'reports:write', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "lastUsedAt" TIMESTAMP(3), "revokedAt" TIMESTAMP(3), "accountId" TEXT NOT NULL, "grantId" TEXT UNIQUE);
CREATE TABLE "Profile" ("id" TEXT PRIMARY KEY, "riotId" TEXT NOT NULL, "riotIdNormalized" TEXT NOT NULL UNIQUE, "accountId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Report" ("id" TEXT PRIMARY KEY, "profileId" TEXT NOT NULL, "completedAt" TIMESTAMP(3) NOT NULL, "champion" TEXT, "gameMode" TEXT, "durationSeconds" INTEGER, "payload" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
ALTER TABLE "DeviceGrant" ADD CONSTRAINT "DeviceGrant_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ApiToken" ADD CONSTRAINT "ApiToken_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ApiToken" ADD CONSTRAINT "ApiToken_grantId_fkey" FOREIGN KEY ("grantId") REFERENCES "DeviceGrant"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Profile" ADD CONSTRAINT "Profile_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Report" ADD CONSTRAINT "Report_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX "DeviceGrant_expiresAt_idx" ON "DeviceGrant"("expiresAt");
CREATE INDEX "DeviceGrant_accountId_idx" ON "DeviceGrant"("accountId");
CREATE INDEX "ApiToken_accountId_revokedAt_idx" ON "ApiToken"("accountId", "revokedAt");
CREATE INDEX "Profile_accountId_idx" ON "Profile"("accountId");
CREATE INDEX "Report_profileId_completedAt_idx" ON "Report"("profileId", "completedAt");
